name: spa_coding_exercise
description: A Flutter SPA search application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.1
  cupertino_icons: ^0.1.3
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  intl_utils: ^1.9.0
  kiwi: ^2.1.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  lint: ^1.5.1
  mockito: ^4.1.3

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true

  assets:
    - resources/fonts/
    - resources/graphics/
    - resources/graphics/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: resources/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: resources/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: resources/fonts/Roboto-Light.ttf
          weight: 300
        - asset: resources/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: resources/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: resources/fonts/Roboto-Italic.ttf
          style: italic
        - asset: resources/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: resources/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: resources/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: resources/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: resources/fonts/Roboto-Black.ttf
          weight: 900
        - asset: resources/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/presentation/localization/translations
  output_dir: lib/presentation/localization/generated
